#!/bin/bash

os_image=$1
run_script=$2

if [ -z "${os_image}" ]; then
  echo "Missing os image"
  exit 1
fi

docker build -q -t "${os_image}" "${os_image}"
docker run --rm -v "$(pwd):/${os_image}" -w "/${os_image}" "${os_image}" /bin/bash "${run_script}"
