#!/bin/bash

if [ "$1" = "--all" ]; then
  find os/* -type f -name Dockerfile | while read -r os_file; do
    bash os/run "$(dirname "${os_file}")" sps/build
  done
  exit 0
fi




echo "Shell: $SHELL $TEST1"

test_shell=$SHELL
test_name=$SHELL_NAME
test_version=$(cat /SHELL_VERSION)

echo "====[ Shell: ${test_name} (${test_shell}) ]===="

find sps/* -type d | while read -r snippet; do
  echo "  - ${snippet}"
  ${test_shell} "${snippet}/code.sh" > "${snippet}/output-actual.txt"

  if [ "$(cat "${snippet}/output-expected.txt")" == "$(cat "${snippet}/output-actual.txt")" ]; then
    test_status="ok"
  else
    test_status="fail"
  fi

  ## Update output-checks.txt
  check_replace="s/^${test_name} ${test_version} .*$/${test_name} ${test_version} ${test_status}/g"
  sed "$check_replace" "${snippet}/output-checks.txt" > "${snippet}/output-checks.tmp"
  mv "${snippet}/output-checks.tmp" "${snippet}/output-checks.txt"
  echo "${test_name} ${test_version} ${test_status}" >> "${snippet}/output-checks.txt"
  sort "${snippet}/output-checks.txt" | uniq > "${snippet}/output-checks.tmp"
  mv "${snippet}/output-checks.tmp" "${snippet}/output-checks.txt"

  sed -n "/## Compatibility/q;p" "${snippet}/README.md" > "${snippet}/README.tmp"

  bash .github/scripts/readme.sh "${snippet}" >> "${snippet}/README.tmp"
  mv "${snippet}/README.tmp" "${snippet}/README.md"
done

echo
