name: Ubuntu Bionic Beaver

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  ubuntu-bionic:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        shells:
          - {shell: dash,        package: dash}
          - {shell: bash,        package: bash}
          - {shell: busybox ash, package: busybox}
          - {shell: ksh,         package: ksh}
          - {shell: mksh,        package: mksh}
          - {shell: posh,        package: posh}
          - {shell: yash,        package: yash}
          - {shell: zsh,         package: zsh}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y ${{ matrix.shells.package }}
      - run: make build shell_name="${{ matrix.shells.shell }}" shell_binary="${{ matrix.shells.shell }}"
      - uses: stefanzweifel/git-auto-commit-action@v4
